
- name: Install generic packages
  yum:
    name:
      - curl
      - git
      - btop
      - zsh
      - yum-utils
    state: present
  become: true
  become_user: root

- name: Copy .zshrc to host
  ansible.builtin.template:
    src: ../../files/zshrc.j2
    dest: ~/.zshrc

- name: Set default shell to zsh
  user:
    name: mlb
    shell: /bin/zsh
  become: true
  become_user: root
