- name: Install neovim package
  yum:
    name:
      - neovim
      - python3-neovim
    state: present
  become: true

- name: Ensure the ~/.config/nvim directory exists
  ansible.builtin.file:
    path: "~/.config/nvim"
    state: directory
  become: true
  become_user: "{{ user }}"

- name: Copy init.vim to host
  ansible.builtin.template:
    src: ../../files/dot/init.vim
    dest: "~/.config/nvim/init.vim"
  become: true
  become_user: "{{ user }}"

- name: Ensure Neovim autoload directory exists
  ansible.builtin.file:
    path: "~/.config/nvim/autoload"
    state: directory
  become: true
  become_user: "{{ user }}"

- name: Ensure vim-plug is installed for Neovim
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~/.config/nvim/autoload/plug.vim"
  become: true
  become_user: "{{ user }}"

- name: Install plugins
  ansible.builtin.command: nvim --headless +PlugInstall +qal
  become: true
  become_user: "{{ user }}"
