- name: Install neovim package
  yum:
    name:
      - neovim
      - python3-neovim
    state: present
  become: true

- name: Ensure the ~/.config/nvim directory exists
  ansible.builtin.file:
    path: "~/.config/nvim"
  become: true
  become_user: "{{ user }}"

- name: Copy init.vim to host
  ansible.builtin.template:
    src: ../../files/dot/init.vim
    dest: "~/.config/nvim/init.vim"
  become: true
  become_user: "{{ user }}"
