- name: Install neovim package
  yum:
    name:
      - neovim
      - python3-neovim
    state: present
  become: true

- name: Copy init.vim to host
  ansible.builtin.template:
    src: ../../files/dot/init.vim
    dest: "~/.config/nvim/init.vim"
  become: true
  become_user: "{{ user }}"
