- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Copy .tmux.conf to host
  ansible.builtin.template:
    src: ../../files/dot/tmux.conf
    dest: "{{ userpath }}/.tmux.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true

- name: Clone tpm
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
  become: true
  become_user: "{{ user }}"

- name: Create catppuccin directory
  file:
    path: ~/.config/tmux/plugins/catppuccin
    state: directory
    mode: "0755"
  become: true
  become_user: "{{ user }}"

- name: Clone catppuccin tmux plugin
  git:
    repo: "https://github.com/catppuccin/tmux.git"
    dest: "~/.config/tmux/plugins/catppuccin/tmux"
    version: "v2.1.2"
  become: true
  become_user: "{{ user }}"
