- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Copy .tmux.conf to host
  ansible.builtin.template:
    src: ../../files/dot/tmux.conf
    dest: "{{ userpath }}/.tmux.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true

- name: Install tpm
  command: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  args:
    creates: ~/.tmux/plugins/tpm
  become: true
  become_user: "{{ user }}"

- name: Install catppuccin
  command: |
    mkdir -p ~/.config/tmux/plugins/catppuccin
    git clone -b v2.1.2 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux
  args:
    creates: ~/.config/tmux/plugins/catppuccin/tmux
  become: true
  become_user: "{{ user }}"
