- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Copy .tmux.conf to host
  ansible.builtin.template:
    src: ../../files/dot/tmux.conf
    dest: "{{ userpath }}/.tmux.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true
