- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Install generic packages
  yum:
    name:
      - zsh
    state: present
  become: true

- name: Set default shell to zsh
  user:
    name: mlb
    shell: /bin/zsh
  become: true

- name: install oh-my-zsh
  command: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh
  become: true
  become_user: "{{ user }}"

- name: install powerlevel10k
  command: |
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
    "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
  args:
    creates: ~/-oh-my-zsh/custom/themes/powerlevel10k
  become: true
  become_user: "{{ user }}"

- name: Copy .zshrc to host
  ansible.builtin.template:
    src: ../../files/dot/zshrc.j2
    dest: "{{ userpath }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true
