- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Install generic packages
  yum:
    name:
      - zsh
    state: present
  become: true

- name: Set default shell to zsh
  user:
    name: mlb
    shell: /bin/zsh
  become: true

- name: install oh-my-zsh
  command: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh
  become: true
  become_user: "{{ user }}"

- name: Clone powerlevel10k
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
  become: true
  become_user: "{{ user }}"

- name: Copy .zshrc to host
  ansible.builtin.template:
    src: ../../files/dot/zshrc.j2
    dest: "~/.zshrc"
  become: true
  become_user: "{{ user }}"

- name: add auto suggestions
  command: |
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
  args:
    creates: ~/.zsh/zsh-autosuggestions
  become: true
  become_user: "{{ user }}"

- name: add syntax highlighting
  command: |
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
  args:
    creates: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
  become: true
  become_user: "{{ user }}"

- name: Copy .p10k.zsh to host
  ansible.builtin.copy:
    src: ../../files/dot/p10k.zsh
    dest: "~/.p10k.zsh"
  become: true
  become_user: "{{ user }}"
