- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Install generic packages
  yum:
    name:
      - zsh
    state: present
  become: true

- name: Copy .zshrc to host
  ansible.builtin.template:
    src: ../../files/dot/zshrc.j2
    dest: "{{ userpath }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true

- name: Set default shell to zsh
  user:
    name: mlb
    shell: /bin/zsh
  become: true

- name: install powerlevel10k
  command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
  args:
    creates: ~/powerlevel10k
  become: true
  become_user: "{{ user }}"

- name: Copy .p10k.zsh to host
  ansible.builtin.copy:
    src: ../../files/dot/p10k.zsh
    dest: "{{ userpath }}/.p10k.zsh"
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true
