- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Install powerline fonts
  command: |
    # clone
    git clone https://github.com/powerline/fonts.git --depth=1
    # install
    cd fonts
    ./install.sh
    # clean-up a bit
    cd ..
    rm -rf fonts
  become: true
  become_user: "{{ user }}"
