- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Install kitty
  yum:
    name:
      - kitty
    state: present
  become: true

- name: Add kitty config
  copy:
    src: ../../files/dot/kitty.conf
    dest: ~/.config/kitty/kitty.conf
  become: true
  become_user: "{{ user }}"
