- name: Ensure the ~/.kube directory exists
  ansible.builtin.file:
    path: "~/.kube"
    state: directory
    mode: "0755"

- name: Add kube config
  copy:
    src: ../../files/kubernetes/config
    dest: ~/.kube/config
  ignore_errors: true
  become: true
