
- name: Set SELinux to permissive temporarily
  ansible.builtin.command: setenforce 0
  become: true

- name: Ensure SELinux is permissive in config file
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=permissive'
  become: true

- name: Set up ip-tables
  ansible.builtin.shell: |
    cat <<EOF | tee /etc/modules-load.d/k8s.conf
    overlay
    br_netfilter
    EOF

    sudo modprobe overlay
    sudo modprobe br_netfilter

    cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.ipv4.ip_forward                 = 1
    EOF
    
    sysctl --system
  become: true
