
- name: Include Vault variables
  include_vars:
    file: ../../vars/vault.yaml

- name: Setup pull secret
  ansible.builtin.shell: |
    kubectl create secret docker-registry regcred \
    --namespace {{ item }} \
    --docker-server={{ github.registry }} \
    --docker-username={{ github.username }} \
    --docker-password={{ github.accessToken }} \
    --docker-email={{ github.email }}
  loop: "{{ namespaces }}"
