
- name: Set fact from comma-separated secrets
  set_fact:
    secrets_str: "{{ secrets }}"

- name: Generate secret dict
  set_fact:
    secrets_dict: "{{ secrets.split(',') | map('split', '=') | map('last') | zip(secrets.split(',') | map('first')) | items2dict }}"
  no_log: true

- name: Debug print the secret dict
  ansible.builtin.debug:
    msg: "{{ secrets_dict }}"

- name: Set json kubernetes secret
  set_fact:
    secret_resource: '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "{{ name }}","namespace": "{{ namespace }}"},"stringData": {"username": "mbrunhoej@outlook.dk", "password": "123" }}'
  no_log: true

- name: Encrypt the Kubernetes secret
  ansible.builtin.shell: |
    echo '{{ secret_resource | to_json }}' \
    | kubeseal --controller-name sealed-secrets --format=yaml
  register: sealed_output

- name: Print the sealed secret
  ansible.builtin.debug:
    msg: "{{ sealed_output.stdout | from_yaml | to_nice_yaml }}"          