

vars_prompt: 
- name: secret_yaml
  prompt: Enter kubernetes secret file content
  private: yes
  no_log: true

- name: Create secret file
  ansible.builtin.shell: |
    echo "{{ secret_yaml }}" > secret.yaml    

- name: Encrypt secret
  ansible.builtin.shell: |
    kubeseal --controller-name sealed-secrets --secret-file secret.yaml --sealed-secret-file sealed-secret.yaml --format=yaml
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"

always:
  - name: Remove secret file
    ansible.builtin.file:
      path: secret.yaml
      state: absent
