

- name: Encrypt the Kubernetes secret
  ansible.builtin.shell: |
    echo '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "tstack-credentials","namespace": "torrent"},"stringData": {"username": "mbrunhoej@outlook.dk", "password": "123" }}' \
    | kubeseal --controller-name sealed-secrets --format=yaml
  register: sealed_output

- name: Print the sealed secret
  ansible.builtin.debug:
    msg: "{{ sealed_output.stdout | to_nice_yaml }}"