
# validate input

- name: Generate secret list
  set_fact:
    secrets_list: "{{ secrets | split(',') }}"
  no_log: false

- name: Debug print the secret list
  ansible.builtin.debug:
    msg: "{{ secrets_list }}"

- name: Create secret dict
  set_fact:
    secrets_dict: {}

- name: Populate secret dict
  block:
    - name: Split secret string into key-value pair
      set_fact:
        secret: {{ item | split('=') }}

    - name: Add entry to dict
      set_fact:
        secrets_dict: "{ secret_dict | combine({secret[0]: secret[1]}) }}"
  loop: "{{ secret_list }}"

- name: Debug print the secret dict
  ansible.builtin.debug:
    msg: "{{ secrets_dict }}"

- name: Set json kubernetes secret
  set_fact:
    secret_resource: '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "{{ name }}","namespace": "{{ namespace }}"},"stringData": {"username": "mbrunhoej@outlook.dk", "password": "123" }}'
  no_log: true

- name: Encrypt the Kubernetes secret
  ansible.builtin.shell: |
    echo '{{ secret_resource | to_json }}' \
    | kubeseal --controller-name sealed-secrets --format=yaml
  register: sealed_output

- name: Print the sealed secret
  ansible.builtin.debug:
    msg: "{{ sealed_output.stdout | from_yaml | to_nice_yaml }}"          