

- name: Create a temporary Kubernetes secret file
  ansible.builtin.shell: |
    echo '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "tstack-credentials","namespace": "torrent"},"stringData": {"username": "mbrunhoej@outlook.dk", "password": "123" }}' > secret.yaml
    
- name: Debug secret_yaml content
  debug:
    msg: "{{ secret_yaml }}"

- name: Debug print the content of a file
  ansible.builtin.shell: |
    cat secret.yaml

- name: Encrypt the Kubernetes secret
  ansible.builtin.shell: |
    kubeseal --controller-name sealed-secrets --secret-file secret.yaml --format=yaml

- name: Remove the temporary secret file
  ansible.builtin.file:
    path: secret.yaml
    state: absent
