

- name: Encrypt the Kubernetes secret
  ansible.builtin.shell: |
    echo '{{ secret_yaml }}' \
    | kubeseal --controller-name sealed-secrets --format=yaml
  register: sealed_output

- name: Print the sealed secret
  ansible.builtin.debug:
    msg: "{{ sealed_output.stdout | from_yaml | to_nice_yaml }}"