

- name: Encrypt the Kubernetes secret
  ansible.builtin.shell: |
    echo '{{ resource }}' \
    | kubeseal --controller-name sealed-secrets --format=yaml
  register: sealed_output
  vars:
    resource: '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "{{ name }}","namespace": "{{ namespace }}"},"stringData": {"username": "mbrunhoej@outlook.dk", "password": "123" }}'

- name: Print the sealed secret
  ansible.builtin.debug:
    msg: "{{ sealed_output.stdout | from_yaml | to_nice_yaml }}"          