
- name: Generate secret list
  set_fact:
    secrets_list: "{{ secrets | split(',') }}"
  no_log: false

- name: Create temporary list of entries
  set_fact:
    secrets_temp_list: []

- name: populate temporary list
  set_fact:
    secrets_temp_list: "{{ secrets_temp_list + [item.split('=')]  }}"
  loop: "{{ secrets_list }}"
  no_log: false

- name: Create secret dict
  set_fact:
    secrets_dict: {}

- name: Add entry to dict
  set_fact:
    secrets_dict: "{{ secrets_dict | combine({item[0]: item[1]}) }}"
  loop: "{{ secrets_temp_list }}"
  no_log: false

- name: Set json kubernetes secret
  set_fact:
    secret_resource: '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "{{ name }}","namespace": "{{ namespace }}"},"stringData": {{ secrets_dict }} }'
  no_log: true

- name: Encrypt the Kubernetes secret
  ansible.builtin.shell: |
    echo '{{ secret_resource | to_json }}' \
    | kubeseal --controller-name sealed-secrets --format=yaml
  register: sealed_output
  no_log: false

- name: Print the sealed secret
  ansible.builtin.debug:
    msg: "{{ sealed_output.stdout | from_yaml | to_nice_yaml }}"
