
- name: Debug print secret
  debug:
    msg: '{{ resource | to_json }}'
  vars:
    resource: '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "{{ name }}","namespace": "{{ namespace }}"},"stringData": {"username": "mbrunhoej@outlook.dk", "password": "123" }}'

- name: Debug print command
  debug:
    msg: echo '{{ resource | to_json }}' | kubeseal --controller-name sealed-secrets --format=yaml
  vars:
    resource: '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "{{ name }}","namespace": "{{ namespace }}"},"stringData": {"username": "mbrunhoej@outlook.dk", "password": "123" }}'

- name: Encrypt the Kubernetes secret
  ansible.builtin.shell: |
    echo '{{ resource | to_json }}' \
    | kubeseal --controller-name sealed-secrets --format=yaml
  register: sealed_output
  vars:
    resource: '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "{{ name }}","namespace": "{{ namespace }}"},"stringData": {"username": "mbrunhoej@outlook.dk", "password": "123" }}'

- name: Print the sealed secret
  ansible.builtin.debug:
    msg: "{{ sealed_output.stdout | from_yaml | to_nice_yaml }}"          