

- name: Encrypt the Kubernetes secret
  ansible.builtin.shell: |
    echo '{"apiVersion": "v1", "kind": "Secret", "metadata": {"name": "tstack-credentials","namespace": "torrent"},"stringData": {"username": "mbrunhoej@outlook.dk", "password": "123" }}' \
    | kubeseal --controller-name sealed-secrets --format=yaml
