
- name: Add prometheus-community Helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install or upgrade prometheus-operator-crds Helm chart
  kubernetes.core.helm:
    name: prometheus-crds
    chart_ref: prometheus-community/prometheus-operator-crds
    chart_version: "15.0.0"
    namespace: kube-system
    release_state: present
