
- name: Add Kubernetes repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes Repository
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
    gpgcheck: true
    repo_gpgcheck: yes
    enabled: true
    gpgkey:
      - https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
    exclude: "kube*"
  become: true

- name: Install Kubernetes packages
  ansible.builtin.yum:
    name:
      - kubelet
      - kubeadm
    state: present
    disable_excludes: kubernetes
  become: true

- name: Enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
  become: true
  retries: 3
  delay: 5
