- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Install kubectx
  ansible.builtin.shell: |
    source <(kubectl completion zsh)
    kubectl krew install ctx
  run_once: true
  become: true
  become_user: "{{ user }}"
