- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Install kubens
  ansible.builtin.shell: |
    source {{ userpath }}/.zshrc && \
    kubectl krew install ns
  run_once: true
  become: true
