
- name: Add Cilium Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install or upgrade Cilium Helm chart
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "1.16.2"
    namespace: kube-system
    values: 
      hubble:
        relay:  
          enabled: true
        ui:
          enabled: true
          ingress:
            enabled: true
            hosts:
              - hubble.priv
      operator:
        replicas: 1
    release_state: present

- name: Get the latest Cilium CLI version
  ansible.builtin.shell: |
    curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
  register: cilium_cli_version

- name: Set CLI architecture
  ansible.builtin.set_fact:
    cli_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Download Cilium CLI and checksum
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.stdout }}/cilium-linux-{{ cli_arch }}.tar.gz"
    dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    mode: '0644'

- name: Download Cilium CLI checksum file
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.stdout }}/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    mode: '0644'

- name: Verify checksum
  ansible.builtin.command:
    cmd: sha256sum --check /tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum
  args:
    chdir: /tmp
  register: checksum_verify
  failed_when: checksum_verify.rc != 0

- name: Extract Cilium CLI binary
  ansible.builtin.unarchive:
    src: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
  become: true

- name: Cleanup downloaded files
  ansible.builtin.file:
    path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    state: absent

- name: Cleanup checksum file
  ansible.builtin.file:
    path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    state: absent
