- name: Include generic variables
  include_vars:
    file: ../../vars/generic.yaml

- name: Install kubens
  ansible.builtin.shell: |
    source <(kubectl completion zsh)
    kubectl krew install ns
  run_once: true
