
- name: Check if node has joined the cluster
  ansible.builtin.command: >
    kubectl get nodes --no-headers -o custom-columns=NAME:.metadata.name
  register: node_check
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
  ignore_errors: true

- name: Check if current node is in the cluster
  ansible.builtin.set_fact:
    node_in_cluster: "{{ inventory_hostname in node_check.stdout_lines | default([]) }}"

- name: Generate kubeadm join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
  run_once: true

- name: join kubernetes node
  ansible.builtin.shell: "{{ join_command.stdout }}"
  become: true
  when: not node_in_cluster

- name: Check if the node has the "not-ready" taint
  ansible.builtin.shell: |
    kubectl describe node $(hostname) | grep "node.kubernetes.io/not-ready:NoSchedule"
  register: taint_check
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
  ignore_errors: true

- name: Untaint the node if "not-ready" taint exists
  ansible.builtin.shell: |
    kubectl taint node $(hostname) node.kubernetes.io/not-ready:NoSchedule-
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
  when: taint_check.rc == 0