- name: Check if node has joined the cluster
  ansible.builtin.shell: |
    kubectl get nodes --no-headers -o custom-columns=NAME:.metadata.name \
    | grep {{ hostvars[inventory_hostname].hostname }}
  register: node_in_cluster
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
  ignore_errors: true

- name: Generate kubeadm join command
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
  run_once: true

- name: join kubernetes node
  ansible.builtin.shell: "{{ join_command.stdout }}"
  become: true
  when: node_in_cluster.rc != 0

- name: Check if the node has the "not-ready" taint
  ansible.builtin.shell: |
    kubectl describe node $HOSTNAME | grep "node.kubernetes.io/not-ready:NoSchedule"
  register: taint_check
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
  ignore_errors: true

- name: Untaint the node if "not-ready" taint exists
  ansible.builtin.shell: |
    kubectl taint node $HOSTNAME node.kubernetes.io/not-ready:NoSchedule-
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
  when: taint_check.rc == 0
