- name: Add nfs csi dricer Helm repository
  kubernetes.core.helm_repository:
    name: csi-driver-nfs
    repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  become: true
  become_user: "{{ user }}"

- name: Install or upgrade nfs csi driver Helm chart
  kubernetes.core.helm:
    name: csi-driver-nfs
    chart_ref: csi-driver-nfs/csi-driver-nfs
    chart_version: "4.9.0"
    namespace: kube-system
    release_state: present
  become: true
  become_user: "{{ user }}"

- name: Delete existing Synology CSI StorageClass
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: synology
  become: true
  become_user: "{{ user }}"

- name: Add Synology CSI StorageClass
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: synology
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: nfs.csi.k8s.io
      parameters:
        server: 192.168.1.10
        share: /volume3/k8sCluster
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      mountOptions:
        - hard
        - nfsvers=4.1
  become: true
  become_user: "{{ user }}"

- name: Delete existing Synology backup CSI StorageClass
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: synology-backup
  become: true
  become_user: "{{ user }}"

- name: Add Synology backup CSI StorageClass
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: synology-backup
      provisioner: nfs.csi.k8s.io
      parameters:
        server: 192.168.1.10
        share: /volume3/k8sCluster-backup
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      mountOptions:
        - hard
        - nfsvers=4.1
  become: true
  become_user: "{{ user }}"
