
- name: Add ingress-nginx Helm repository
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Ensure ingress-nginx namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ingress-nginx

- name: Install or upgrade ingress-nginx Helm chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "4.11.3"
    namespace: ingress-nginx
    values:
      controller:
        kind: DaemonSet
        hostNetwork: true
        ingressClassResource:
          default: true
    release_state: present
