- name: Include Kubernetes variables
  include_vars:
    file: ../../vars/kubernetes.yaml

- name: Add metallb Helm repository
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Ensure metallb-system namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: metallb-system

- name: Install or upgrade metallb Helm chart
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version: "0.14.8"
    namespace: metallb-system
    release_state: present

- name: Check if the pods are ready
  ansible.builtin.shell: |
    kubectl -n metallb-system rollout status daemonset metallb-speaker --timeout 120s

- name: Create ip-address pool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: pool
        namespace: metallb-system
      spec:
        addresses:
        - "{{ metallb.addressRange }}"

- name: Create BGPadvertisement
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: BGPAdvertisement
      metadata:
        name: advertiser
        namespace: metallb-system
      spec:
        ipAddressPools:
        - pool

- name: Create L2Advertisement
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2-adviertisement
        namespace: metallb-system
      spec:
        ipAddressPools:
        - pool

- name: Create BGP peer
  kubernetes.core.k8s:
    state: present
    definition: 
      apiVersion: metallb.io/v1beta2
      kind: BGPPeer
      metadata:
        name: "{{ metallb.peerName }}"
        namespace: metallb-system
      spec:
        myASN: 64512
        peerASN: 64512
        peerAddress: "{{ metallb.peerAddress }}"
        peerPort: 179