- name: Add metrics-server Helm repository
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: https://kubernetes-sigs.github.io/metrics-server/

- name: Install or upgrade metrics-server Helm chart
  kubernetes.core.helm:
    name: metrics-server
    chart_ref: metrics-server/metrics-server
    chart_version: "3.12.2"
    namespace: kube-system
    values:
      args:
        - --kubelet-insecure-tls
    release_state: present
