- name: Add ingress-nginx Helm repository
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Ensure ingress-nginx namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ingress-nginx

- name: Install or upgrade ingress-nginx Helm chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "4.11.3"
    namespace: ingress-nginx
    values:
      controller:
        kind: DaemonSet
        hostNetwork: true
        ingressClassResource:
          default: true
    release_state: present

- name: Copy public key to host
  ansible.builtin.template:
    src: ../../files/certificates/lan/wildcard.lan.crt
    dest: "{{ playbook_dir }}/wildcard.lan.crt"

- name: Copy private key to host
  ansible.builtin.template:
    src: ../../files/certificates/lan/wildcard.lan.key
    dest: "{{ playbook_dir }}/wildcard.lan.key"

- name: debug ls
  shell: ls "{{ playbook_dir }}"
  register: playbook_dir_content

- name: debug
  debug:
    msg: "{{ playbook_dir_content.stdout_lines }}"


- name: Create Kubernetes TLS secret
  kubernetes.core.k8s:
    state: present
    namespace: ingress-nginx
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: lan-certificate
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ lookup('file', playbook_dir + '/wildcard.lan.crt') | b64encode }}"
        tls.key: "{{ lookup('file', playbook_dir + '/wildcard.lan.key') | b64encode }}"

