
- name: Add sealed secrets Helm repository
  kubernetes.core.helm_repository:
    name: sealed-secrets
    repo_url: https://bitnami-labs.github.io/sealed-secrets

- name: Install or upgrade sealed secrets Helm chart
  kubernetes.core.helm:
    name: sealed-secrets
    chart_ref: sealed-secrets/sealed-secrets
    chart_version: "2.16.1"
    namespace: kube-system
    release_state: present
  