
- name: Include Kubernetes variables
  include_vars:
    file: ../../vars/kubernetes.yaml

- name: Include Vault variables
  include_vars:
    file: ../../vars/vault.yaml

- name: Add argocd Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Ensure argocd namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd

- name: Install or upgrade argocd Helm chart
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    chart_version: "7.7.12"
    namespace: argocd
    values:
      crds:
        install: true
        keep: false
      global:
        domain: "{{ argocd.hostname }}"
      server:
        ingress:
          enabled: true
          ingressClassName: nginx
      redis: 
        enabled: true
      dex:
        enabled: false
      configs:
        secret:
          argocdServerAdminPassword: "{{ argocd.password }}"
        repositories:
          helm-repo:
            url: ghcr.io/matlerbru/charts
            name: helm-repo
            type: helm
            password: "{{ github.password }}"
            username: "{{ github.accessToken }}"
          kubernetes-repo:
            url: git@github.com:matlerbru/kubernetes.git
            name: kubernetes-repo
            type: git
            sshPrivateKey: "{{ lookup('file', '../../files/ssh/ansible/id-ansible') }}"
        params:
          server.insecure: true
    release_state: present
