- name: Taint node
  ansible.builtin.shell: |
      kubectl taint node $HOSTNAME {{ item.key }}:{{ item.effect }} --overwrite
  loop: "{{ hostvars[inventory_hostname].taints }}"
  when: hostvars[inventory_hostname].taints is defined
  delegate_to: "{{ groups['kubernetesMasterNodes'][0] }}"
