
- name: Disable firewalld
  hosts: kubernetesMasterNodes:kubernetesWorkerNodes
  gather_facts: false
  
  tasks:
    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: no
      become: true
