- name: Disable traefik
  hosts: kubernetesMasterNodes
  vars_files:
    - ../vars/vault.yaml
    - ../vars/kubernetes.yaml

  tasks:

    - block:

        - name: Remove traefik manifest
          ansible.builtin.shell: |
            rm -rf /var/lib/rancher/k3s/server/manifests/traefik.yaml
          become: true

        - name: Check if traefik is installed
          ansible.builtin.shell: |
            kubectl -n kube-system get deploy | grep traefik || echo ""
          register: traefik_is_installed
          delegate_to: alteret.master01
          run_once: true
          
        - name: Remove traefik helm chart
          ansible.builtin.shell: |
            helm uninstall traefik traefik-crd -n kube-system
          when: traefik_is_installed.stdout != ""
          delegate_to: alteret.master01
          run_once: true

        - name: Restart k3s
          ansible.builtin.shell: |
            systemctl restart k3s
          become: true

