- name: Install packages on kubernetes nodes
  hosts: kubernetesMasterNodes:kubernetesWorkerNodes
  vars_files:
    - ../vars/kubernetes.yaml

  tasks:

    - name: Install generic packages
      yum:
        name:
          - curl
          - git
          - btop
          - zsh
        state: present
      become: true

    - name: Move .zshrc to home
      ansible.builtin.copy:
        src: ~/resources/zsh/.zshrc
        dest: ~/.zshrc
        remote_src: true
        follow: true

    - name: Move powerlevel10k
      ansible.builtin.copy:
        src: ~/resources/zsh/powerlevel10k
        dest: ~/
        remote_src: true
        follow: true

    - name: Set default shell to zsh
      user:
        name: "{{ defaultUser }}"
        shell: /bin/zsh
      become: true
