
- name: Install cilium
  hosts: kubernetesMasterNodes
  vars_files:
    - ../vars/vault.yaml
    - ../vars/kubernetes.yaml

  tasks:

    - block:

      - name: Add cilium helm repo
        ansible.builtin.shell: |
          helm repo add cilium https://helm.cilium.io/ && \
          helm repo update

      - name: Install cilium helm chart
        ansible.builtin.shell: |
          helm upgrade --install \
          cilium cilium/cilium --version 1.16.2 \
          --namespace kube-system \
          --reuse-values \
          -f ~/resources/helm-values/cilium.yaml

      when: inventory_hostname == groups['kubernetesMasterNodes'][0]
