
- name: Install prometheus crds
  hosts: kubernetesMasterNodes
  gather_facts: false

  tasks:

    - block:

      - name: Add sealed secrets helm repo
        ansible.builtin.shell: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && \
          helm repo update

      - name: Install sealed secrets helm chart
        ansible.builtin.shell: |
          helm upgrade --install prometheus-crds \
          prometheus-community/prometheus-operator-crds --version 15.0.0 \
          --namespace kube-system \

      when: inventory_hostname == groups['kubernetesMasterNodes'][0] 
