
- name: Setup sealed secrets
  hosts: kubernetesMasterNodes
  gather_facts: false

  tasks:

    - block:

      - name: Add sealed secrets helm repo
        ansible.builtin.shell: |
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets && \
          helm repo update

      - name: Install sealed secrets helm chart
        ansible.builtin.shell: |
          helm upgrade --install sealed-secrets \
          sealed-secrets/sealed-secrets --version 2.16.1 \
          --namespace kube-system \
          -f ~/resources/helm-values/sealed-secrets.yaml

      when: inventory_hostname == groups['kubernetesMasterNodes'][0] 

    - name: Install kubeseal
      ansible.builtin.shell: |
        KUBESEAL_VERSION=$(curl -s https://api.github.com/repos/bitnami-labs/sealed-secrets/tags | jq -r '.[0].name' | cut -c 2-) &&
        if [ -z "$KUBESEAL_VERSION" ]; then
          echo "Failed to fetch the latest KUBESEAL_VERSION"
          exit 1
        fi
        curl -OL "https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION}/kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz"
        tar -xvzf kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz kubeseal
        sudo install -m 755 kubeseal /usr/local/bin/kubeseal

      when: inventory_hostname == groups['kubernetesMasterNodes'][0] 