- name: Setup storage provisioners
  hosts: kubernetesMasterNodes
  vars_files:
    - ../vars/vault.yaml
    - ../vars/kubernetes.yaml

  tasks:

    - block:

      - name: Add nfs csi driver helm repo
        ansible.builtin.shell: |
          helm repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts && \
          helm repo update

      - name: Install nfs csi driver helm chart
        ansible.builtin.shell: |
          helm upgrade --install csi-driver-nfs \
          csi-driver-nfs/csi-driver-nfs --version 4.9.0 \
          --namespace kube-system

      - name: Add synology csi
        ansible.builtin.shell: |
          echo " 
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: synology
          provisioner: nfs.csi.k8s.io
          parameters:
            server: 192.168.1.10
            share: /volume3/k8sCluster
          reclaimPolicy: Retain
          volumeBindingMode: Immediate
          mountOptions:
            - hard
            - nfsvers=4.1" | kubectl apply -f -

      - name: Add synology-backup csi
        ansible.builtin.shell: |
          echo " 
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: synology-backup
          provisioner: nfs.csi.k8s.io
          parameters:
            server: 192.168.1.10
            share: /volume3/k8sCluster-backup
          reclaimPolicy: Retain
          volumeBindingMode: Immediate
          mountOptions:
            - hard
            - nfsvers=4.1" | kubectl apply -f -

      when: inventory_hostname == groups['kubernetesMasterNodes'][0]