- name: Setup kubernetes cluster
  hosts: kubernetesMasterNodes
  vars_files:
    - ../vars/vault.yaml
    - ../vars/kubernetes.yaml

  tasks:

    - block:

        - name: Initialize k3s cluster
          ansible.builtin.shell: |
            curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --flannel-backend none --disable-network-policy --disable=servicelb --token {{ kubernetes.k3s_token }}
          register: result
          become: true

        - name: Register current user
          ansible.builtin.command: whoami
          register: current_user

        - name: Link kubeconfig
          ansible.builtin.shell: |
            mkdir -p ~/.kube && \
            ln -sf /etc/rancher/k3s/k3s.yaml ~/.kube/config

        - name: Chown kubeconfig
          ansible.builtin.file:
            path: /home/{{ current_user.stdout }}/.kube/config
            owner: "{{ current_user.stdout }}"
            group: "{{ current_user.stdout }}" 
          become: true

      when: inventory_hostname == groups['kubernetesMasterNodes'][0]
