
- name: Setup sealed secrets
  hosts: kubernetesMasterNodes
  gather_facts: false

  tasks:

    - block:

      - name: Add sealed secrets helm repo
        ansible.builtin.shell: |
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets && \
          helm repo update

      - name: Install sealed secrets helm chart
        ansible.builtin.shell: |
          helm upgrade --install sealed-secrets \
          sealed-secrets/sealed-secrets --version 2.16.1 \
          --namespace kube-system \
          -f ~/resources/helm-values/sealed-secrets.yaml

      when: inventory_hostname == groups['kubernetesMasterNodes'][0] 
