- name: Encrypt kubernetes secret using sealed-secrets
  hosts: kubernetesMasterNodes

  tasks:

  - name: Install generic packages
    include_tasks: ../roles/kubernetes/encrypt-secret.yaml

  run_once: true