- name: Encrypt kubernetes secret using sealed-secrets
  hosts: kubernetesMasterNodes
  vars_prompt:
    - name: secret_yaml
      prompt: Enter Kubernetes secret file content
      private: yes
      
  tasks:

  - name: Encrypt secret
    include_tasks: ../roles/kubernetes/encrypt-secret.yaml

  run_once: true