
- name: Report PVC table
  hosts: kubernetesMasterNodes
  gather_facts: false

  tasks:

    - name: Fetch PVC table
      ansible.builtin.shell: |
        kubectl get pvc --all-namespaces  | column -t
      register: kubectl_pvc_list
      when: inventory_hostname == groups['kubernetesMasterNodes'][0] 

    - name: Print PVC table
      debug:
        msg: "{{ kubectl_pvc_list.stdout }}"
      when: inventory_hostname == groups['kubernetesMasterNodes'][0] 
