- name: Setup desktop
  hosts: desktop

  tasks:

  - name: Install generic packages
    include_tasks: ../roles/generic/install-packages.yaml

  - name: Install desktop packages
    include_tasks: ../roles/desktop/install-packages.yaml

  - name: Setup wezterm
    include_tasks: ../roles/desktop/setup-wezterm.yaml

  - name: Setup zsh
    include_tasks: ../roles/generic/setup-zsh.yaml

  - name: Setup tmux
    include_tasks: ../roles/generic/setup-tmux.yaml

  - name: Install neovim
    include_tasks: ../roles/generic/install-neovim.yaml

  - name: Add ansible ssh keys
    include_tasks: ../roles/generic/add-ssh-ansible-key.yaml

  - name: Set hostname
    include_tasks: ../roles/generic/set-hostname.yaml

  - name: Install kubernetes access
    include_tasks: ../roles/generic/install-kubernetes-access.yaml
