- name: Setup desktop
  hosts: desktop

  tasks:

  - name: Install generic packages
    include_tasks: ../roles/generic/install-packages.yaml

  - name: Install neovim
    include_tasks: ../roles/generic/install-neovim.yaml

  - name: Add ansible ssh keys
    include_tasks: ../roles/generic/add-ssh-ansible-key.yaml

  - name: Set hostname
    include_tasks: ../roles/generic/set-hostname.yaml

  - name: Install kubernetes access
    include_tasks: ../roles/generic/install-kubernetes-access.yaml

  - name: Copy kube config
    include_tasks: ../roles/generic/copy-kube-config.yaml